server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon

eureka:
  client:
    eureka-server-port: 8761
    service-url: 
      defaultZone: http://discovery:${eureka.client.eureka-server-port}/eureka/
    instance:
      preferIpAddress: true

# 服务提供者地址
microservice-provider-user:
  serviceUrl: http://microservice-provider-user